version: '3.9'

services:
  focus-list-rabbit:
    image: rabbitmq:3-management
    container_name: focus-list-rabbit
    hostname: focus-list-rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    networks:
      - main-network

  register-api:
    container_name: register-api
    build: 
      context: apps/register
      dockerfile: Dockerfile.prod
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3003"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      focus-list-rabbit:
        condition: service_healthy
    ports:
      - 3003:3003
    networks:
      - main-network

  login-api:
    container_name: login-api
    build: 
      context: apps/login
      dockerfile: Dockerfile.prod
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3004"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      focus-list-rabbit:
        condition: service_healthy
    ports:
      - 3004:3004
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
