# Stage 1: Build
FROM node:16-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./src ./src
COPY tsconfig.build.json tsconfig.build.json
COPY tsconfig.json tsconfig.json

RUN npm run build

# Stage 2: Run
FROM node:16-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3004

CMD ["node", "dist/main"]
